homeassistant:
  name: Home
  country: UA
  currency: UAH
  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
  elevation: 50
  unit_system: metric
  time_zone: Europe/Kiev
  packages: !include_dir_merge_named includes
  auth_providers:
   - type: homeassistant
  whitelist_external_dirs :
   - /config

default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

panel_custom:
  - name: server_state
    sidebar_title: 'System'
    sidebar_icon: mdi:server
    js_url: /api/hassio/app/entrypoint.js
    url_path: 'hassio/system'
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator

